/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\Perso\Jeremie-pires.github.io\public\models\chambre.glb --transform --types 
Files: c:\Perso\Jeremie-pires.github.io\public\models\chambre.glb [62.22MB] > C:\Perso\Jeremie-pires.github.io\chambre-transformed.glb [5.49MB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Geom3D: THREE.Mesh
    Geom3D_1: THREE.Mesh
    Geom3D_: THREE.Mesh
    Geom3D_Pillow_mi0: THREE.Mesh
    Geom3D_2: THREE.Mesh
    Geom3D_3: THREE.Mesh
    Geom3D_4: THREE.Mesh
    ['Geom3D_Componente#18']: THREE.Mesh
    ['Geom3D_Componente#19']: THREE.Mesh
    Geom3D_5: THREE.Mesh
    Geom3D_6: THREE.Mesh
    Geom3D_7: THREE.Mesh
    Geom3D_Skrew: THREE.Mesh
    Geom3D_Prop: THREE.Mesh
    Geom3D_8: THREE.Mesh
    Geom3D_9: THREE.Mesh
    Geom3D_10: THREE.Mesh
    Geom3D_11: THREE.Mesh
    Geom3D_12: THREE.Mesh
    Geom3D_13: THREE.Mesh
    Geom3D_14: THREE.Mesh
    Geom3D_15: THREE.Mesh
    Geom3D__1: THREE.Mesh
    Geom3D_16: THREE.Mesh
    Geom3D_17: THREE.Mesh
    Geom3D_18: THREE.Mesh
    Geom3D_19: THREE.Mesh
    Geom3D_20: THREE.Mesh
    Geom3D_21: THREE.Mesh
    Geom3D_22: THREE.Mesh
    Geom3D_23: THREE.Mesh
    Geom3D_24: THREE.Mesh
    Geom3D_25: THREE.Mesh
    Geom3D_26: THREE.Mesh
    Geom3D_27: THREE.Mesh
    Geom3D_28: THREE.Mesh
    Geom3D_29: THREE.Mesh
    Geom3D_30: THREE.Mesh
    Geom3D_31: THREE.Mesh
    Geom3D_32: THREE.Mesh
    Geom3D_33: THREE.Mesh
    Geom3D_MALALS: THREE.Mesh
    Geom3D_34: THREE.Mesh
    Geom3D_35: THREE.Mesh
    Geom3D_36: THREE.Mesh
    Geom3D_37: THREE.Mesh
    Geom3D_38: THREE.Mesh
    Geom3D_39: THREE.Mesh
    Geom3D_40: THREE.Mesh
    Geom3D_41: THREE.Mesh
    Geom3D_42: THREE.Mesh
    Geom3D_43: THREE.Mesh
    Geom3D__2: THREE.Mesh
    Geom3D_44: THREE.Mesh
    Geom3D_45: THREE.Mesh
    Geom3D_46: THREE.Mesh
    Geom3D_47: THREE.Mesh
    Geom3D_48: THREE.Mesh
    Geom3D_49: THREE.Mesh
    Geom3D_50: THREE.Mesh
    Geom3D_51: THREE.Mesh
    Geom3D_52: THREE.Mesh
    Geom3D__3: THREE.Mesh
    Geom3D__4: THREE.Mesh
    Geom3D_53: THREE.Mesh
    Geom3D_54: THREE.Mesh
    Geom3D_55: THREE.Mesh
    Geom3D__5: THREE.Mesh
    Geom3D__6: THREE.Mesh
    Geom3D_56: THREE.Mesh
    Geom3D_57: THREE.Mesh
    Geom3D_58: THREE.Mesh
    ['Geom3D_Interior_Wood_Door_-_single']: THREE.Mesh
    Geom3D_59: THREE.Mesh
    Geom3D_60: THREE.Mesh
    Geom3D_61: THREE.Mesh
    Geom3D_62: THREE.Mesh
    Geom3D_63: THREE.Mesh
    Geom3D_64: THREE.Mesh
    Geom3D_65: THREE.Mesh
    Geom3D_66: THREE.Mesh
    Geom3D_67: THREE.Mesh
    Geom3D_68: THREE.Mesh
    ['Geom3D_4x1x1_vert_hinge_double#2']: THREE.Mesh
    ['Geom3D_2x1x1_vert_hinge_B#1']: THREE.Mesh
    Geom3D__7: THREE.Mesh
    Geom3D__8: THREE.Mesh
    Geom3D_1x1_technic_peg: THREE.Mesh
    ['Geom3D_1x1x13_cylinder#2']: THREE.Mesh
    Geom3D_69: THREE.Mesh
    Geom3D_70: THREE.Mesh
    Geom3D_71: THREE.Mesh
    Geom3D_72: THREE.Mesh
    Geom3D__9: THREE.Mesh
    Geom3D_73: THREE.Mesh
    ['Geom3D_Component#83']: THREE.Mesh
    Geom3D_74: THREE.Mesh
    Geom3D_75: THREE.Mesh
    Geom3D_76: THREE.Mesh
    Geom3D__10: THREE.Mesh
    Geom3D__11: THREE.Mesh
    Geom3D_77: THREE.Mesh
    Geom3D_78: THREE.Mesh
    Geom3D_79: THREE.Mesh
    Geom3D_80: THREE.Mesh
    Geom3D_81: THREE.Mesh
    Geom3D_82: THREE.Mesh
    Geom3D_83: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    ['[Steel Brushed Stainless]']: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    ['[Metal_Aluminum_Anodized]']: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshStandardMaterial
    PaletteMaterial013: THREE.MeshStandardMaterial
    PaletteMaterial014: THREE.MeshStandardMaterial
    PaletteMaterial015: THREE.MeshStandardMaterial
    PaletteMaterial016: THREE.MeshStandardMaterial
    ['Office Chair_Material6']: THREE.MeshStandardMaterial
    PaletteMaterial017: THREE.MeshStandardMaterial
    PaletteMaterial018: THREE.MeshStandardMaterial
    PaletteMaterial019: THREE.MeshStandardMaterial
    PaletteMaterial020: THREE.MeshStandardMaterial
    gfirelogosadfasdfasdfasdfasdfsadfs: THREE.MeshStandardMaterial
    detai1asdfasdfasdfdasfsadf0as2df0s0: THREE.MeshStandardMaterial
    Material1sadfdsafsdafasdfdsa: THREE.MeshStandardMaterial
    Material2sadfasdfasdfasdfas: THREE.MeshStandardMaterial
    PaletteMaterial021: THREE.MeshStandardMaterial
    PaletteMaterial022: THREE.MeshStandardMaterial
    PaletteMaterial023: THREE.MeshStandardMaterial
    PaletteMaterial024: THREE.MeshStandardMaterial
    teladesligada_dsafasfasf01asd5f01as0f1s5dw: THREE.MeshStandardMaterial
    PaletteMaterial025: THREE.MeshStandardMaterial
    Material1asdfasdfasdfw: THREE.MeshStandardMaterial
    borda_dfsafkasdjfiaosdfasdfas0e15061hgf5d60h16fg50h1f601adasad: THREE.MeshStandardMaterial
    pretoasdfasfasfsfwfwfwfw: THREE.MeshStandardMaterial
    PaletteMaterial026: THREE.MeshStandardMaterial
    PaletteMaterial027: THREE.MeshStandardMaterial
    PaletteMaterial028: THREE.MeshStandardMaterial
    PaletteMaterial029: THREE.MeshStandardMaterial
    Valla_anudada_en_forma_de_rombosdfasdfasfdasw: THREE.MeshStandardMaterial
    fdasfasfasfasfadfw: THREE.MeshStandardMaterial
    PaletteMaterial030: THREE.MeshStandardMaterial
    PaletteMaterial031: THREE.MeshStandardMaterial
    PaletteMaterial032: THREE.MeshStandardMaterial
    PaletteMaterial033: THREE.MeshStandardMaterial
    PaletteMaterial034: THREE.MeshStandardMaterial
    PaletteMaterial035: THREE.MeshStandardMaterial
    PaletteMaterial036: THREE.MeshStandardMaterial
    PaletteMaterial037: THREE.MeshStandardMaterial
    PaletteMaterial038: THREE.MeshStandardMaterial
    ['Metal Corrugated Shiny']: THREE.MeshStandardMaterial
    ['1']: THREE.MeshStandardMaterial
    ['2']: THREE.MeshStandardMaterial
    ['20240228_144641']: THREE.MeshStandardMaterial
    ['20240228_144008']: THREE.MeshStandardMaterial
    ['20240228_144054']: THREE.MeshStandardMaterial
    PaletteMaterial039: THREE.MeshStandardMaterial
    PaletteMaterial040: THREE.MeshStandardMaterial
    PaletteMaterial041: THREE.MeshStandardMaterial
    PaletteMaterial042: THREE.MeshStandardMaterial
    PaletteMaterial043: THREE.MeshStandardMaterial
    PaletteMaterial044: THREE.MeshStandardMaterial
    PaletteMaterial045: THREE.MeshStandardMaterial
    PaletteMaterial046: THREE.MeshStandardMaterial
    PaletteMaterial047: THREE.MeshStandardMaterial
    PaletteMaterial048: THREE.MeshStandardMaterial
    PaletteMaterial049: THREE.MeshStandardMaterial
    Tela: THREE.MeshStandardMaterial
    PaletteMaterial050: THREE.MeshStandardMaterial
    Plywood_03_1K: THREE.MeshStandardMaterial
    Plywood_08_1K: THREE.MeshStandardMaterial
    ['[Wood_Cherry_Original]']: THREE.MeshStandardMaterial
    PaletteMaterial051: THREE.MeshStandardMaterial
    PaletteMaterial052: THREE.MeshStandardMaterial
    PaletteMaterial053: THREE.MeshStandardMaterial
    ['*3']: THREE.MeshStandardMaterial
    PaletteMaterial054: THREE.MeshStandardMaterial
    PaletteMaterial055: THREE.MeshStandardMaterial
    PaletteMaterial056: THREE.MeshStandardMaterial
    PaletteMaterial057: THREE.MeshStandardMaterial
    PaletteMaterial058: THREE.MeshStandardMaterial
    PaletteMaterial059: THREE.MeshStandardMaterial
    PaletteMaterial060: THREE.MeshStandardMaterial
    PaletteMaterial061: THREE.MeshStandardMaterial
    PaletteMaterial062: THREE.MeshStandardMaterial
    PaletteMaterial063: THREE.MeshStandardMaterial
    PaletteMaterial064: THREE.MeshStandardMaterial
    PaletteMaterial065: THREE.MeshStandardMaterial
    ['*1']: THREE.MeshStandardMaterial
    ['*6']: THREE.MeshStandardMaterial
    ['*7']: THREE.MeshStandardMaterial
    PaletteMaterial066: THREE.MeshStandardMaterial
    PaletteMaterial067: THREE.MeshStandardMaterial
    PaletteMaterial068: THREE.MeshStandardMaterial
    PaletteMaterial069: THREE.MeshStandardMaterial
    ['*9']: THREE.MeshStandardMaterial
    PaletteMaterial070: THREE.MeshStandardMaterial
    PaletteMaterial071: THREE.MeshStandardMaterial
    PaletteMaterial072: THREE.MeshStandardMaterial
    ['*4']: THREE.MeshStandardMaterial
    ['*10']: THREE.MeshStandardMaterial
    ['*8']: THREE.MeshStandardMaterial
    PaletteMaterial073: THREE.MeshStandardMaterial
    PaletteMaterial074: THREE.MeshStandardMaterial
    Material__3_0_6: THREE.MeshStandardMaterial
    ['*5']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chambre-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geom3D.geometry} material={materials.PaletteMaterial001} position={[1.743, 0.084, -1.786]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_1.geometry} material={materials.PaletteMaterial002} position={[1.63, 0.281, -0.088]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.022, 0.021, 0.021]} />
      <mesh geometry={nodes.Geom3D_.geometry} material={materials.PaletteMaterial003} position={[0.2, 0.436, -0.328]} rotation={[-2.692, -0.06, -1.501]} scale={[0.021, 0.025, 0.017]} />
      <mesh geometry={nodes.Geom3D_Pillow_mi0.geometry} material={materials.PaletteMaterial004} position={[1.778, -0.079, -2.345]} rotation={[-1.057, 0.017, -3.089]} scale={0.001} />
      <mesh geometry={nodes.Geom3D_2.geometry} material={materials.PaletteMaterial005} position={[0.862, 0.139, -0.911]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes.Geom3D_3.geometry} material={materials.PaletteMaterial006} position={[1.743, 0.191, -0.493]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.021, 0.021, 0.021]} />
      <mesh geometry={nodes.Geom3D_4.geometry} material={materials.PaletteMaterial007} position={[1.546, 0.218, -1.734]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.021, 0.02, 0.02]} />
      <mesh geometry={nodes['Geom3D_Componente#18'].geometry} material={nodes['Geom3D_Componente#18'].material} position={[2.853, 0.069, -0.002]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.02} />
      <mesh geometry={nodes['Geom3D_Componente#19'].geometry} material={materials['[Steel Brushed Stainless]']} position={[2.838, 1.979, -0.47]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Geom3D_5.geometry} material={materials.PaletteMaterial008} position={[0.016, 0.084, -2.469]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_6.geometry} material={materials.PaletteMaterial009} position={[0.016, 0.084, -2.469]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_7.geometry} material={materials.PaletteMaterial010} position={[0.101, 0.084, -2.684]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_Skrew.geometry} material={materials['[Metal_Aluminum_Anodized]']} position={[0.458, 0.852, -4.098]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.002} />
      <mesh geometry={nodes.Geom3D_Prop.geometry} material={materials.PaletteMaterial011} position={[0.111, 0.084, -4.024]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_8.geometry} material={materials.PaletteMaterial012} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_9.geometry} material={materials.PaletteMaterial013} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_10.geometry} material={materials.PaletteMaterial014} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_11.geometry} material={materials.PaletteMaterial015} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_12.geometry} material={materials.PaletteMaterial016} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_13.geometry} material={materials['Office Chair_Material6']} position={[1.028, 0.084, -3.382]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_14.geometry} material={materials.PaletteMaterial017} position={[0.595, 0.884, -3.656]} rotation={[-Math.PI / 2, 0, 1.566]} scale={[0.025, 0.025, 0.023]} />
      <mesh geometry={nodes.Geom3D_15.geometry} material={materials.PaletteMaterial018} position={[0.595, 0.884, -3.656]} rotation={[-Math.PI / 2, 0, 1.566]} scale={[0.025, 0.025, 0.023]} />
      <mesh geometry={nodes.Geom3D__1.geometry} material={materials.PaletteMaterial019} position={[0.414, 0.895, -3.333]} rotation={[0, -1.55, Math.PI]} scale={[0.027, 0.025, 0.027]} />
      <mesh geometry={nodes.Geom3D_16.geometry} material={materials.PaletteMaterial020} position={[0.559, 0.904, -3.118]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_17.geometry} material={materials.gfirelogosadfasdfasdfasdfasdfsadfs} position={[0.648, 0.884, -3.081]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_18.geometry} material={materials.detai1asdfasdfasdfdasfsadf0as2df0s0} position={[0.648, 0.884, -3.081]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_19.geometry} material={materials.Material1sadfdsafsdafasdfdsa} position={[0.648, 0.884, -3.081]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_20.geometry} material={materials.Material2sadfasdfasdfasdfas} position={[0.648, 0.884, -3.081]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_21.geometry} material={materials.PaletteMaterial021} position={[0.524, 0.898, -3.162]} rotation={[-Math.PI / 2, 0, 1.592]} scale={[0.027, 0.027, 0.025]} />
      <mesh geometry={nodes.Geom3D_22.geometry} material={materials.PaletteMaterial022} position={[0.189, 1.146, -3.291]} rotation={[-Math.PI / 2, 0, 1.592]} scale={0.031} />
      <mesh geometry={nodes.Geom3D_23.geometry} material={materials.PaletteMaterial023} position={[0.253, 0.98, -3.324]} rotation={[0, -1.55, 0]} scale={[-0.027, 0.027, 0.027]} />
      <mesh geometry={nodes.Geom3D_24.geometry} material={materials.PaletteMaterial024} position={[0.26, 0.976, -3.01]} rotation={[-Math.PI / 2, 0, 1.592]} scale={0.031} />
      <mesh geometry={nodes.Geom3D_25.geometry} material={materials.teladesligada_dsafasfasf01asd5f01as0f1s5dw} position={[0.26, 0.976, -3.01]} rotation={[-Math.PI / 2, 0, 1.592]} scale={0.031} />
      <mesh geometry={nodes.Geom3D_26.geometry} material={materials.PaletteMaterial025} position={[0.271, 0.887, -3.457]} rotation={[1.57, -0.033, 1.55]} scale={0.027} />
      <mesh geometry={nodes.Geom3D_27.geometry} material={materials.Material1asdfasdfasdfw} position={[0.342, 0.882, -3.821]} rotation={[-Math.PI / 2, 0, -1.55]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_28.geometry} material={materials.borda_dfsafkasdjfiaosdfasdfas0e15061hgf5d60h16fg50h1f601adasad} position={[0.342, 0.882, -3.821]} rotation={[-Math.PI / 2, 0, -1.55]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_29.geometry} material={materials.pretoasdfasfasfsfwfwfwfw} position={[0.309, 0.95, -3.869]} rotation={[-Math.PI, -0.005, -Math.PI]} scale={[-0.025, 0.025, 0.023]} />
      <mesh geometry={nodes.Geom3D_30.geometry} material={materials.PaletteMaterial026} position={[0.348, 0.988, -3.848]} rotation={[-Math.PI, -0.005, -Math.PI]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_31.geometry} material={materials.PaletteMaterial027} position={[0.408, 1.053, -3.854]} rotation={[-Math.PI, -0.005, Math.PI / 7]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_32.geometry} material={materials.PaletteMaterial028} position={[0.344, 0.984, -3.853]} rotation={[-Math.PI, -0.005, -Math.PI]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_33.geometry} material={materials.PaletteMaterial029} position={[0.343, 0.984, -3.871]} rotation={[-Math.PI, -0.005, -Math.PI]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_MALALS.geometry} material={materials.Valla_anudada_en_forma_de_rombosdfasdfasfdasw} position={[0.063, 1.132, -3.922]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_34.geometry} material={materials.fdasfasfasfasfadfw} position={[0.062, 1.384, -3.844]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_35.geometry} material={materials.PaletteMaterial030} position={[0.062, 1.384, -3.844]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_36.geometry} material={materials.PaletteMaterial031} position={[0.522, 1.401, -3.895]} rotation={[-Math.PI, -0.005, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_37.geometry} material={materials.PaletteMaterial032} position={[0.515, 1.41, -3.892]} rotation={[-Math.PI, -0.005, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_38.geometry} material={materials.PaletteMaterial033} position={[0.515, 1.41, -3.892]} rotation={[-Math.PI, -0.005, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_39.geometry} material={materials.PaletteMaterial034} position={[0.56, 1.401, -3.895]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_40.geometry} material={materials.PaletteMaterial035} position={[0.56, 1.401, -3.895]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_41.geometry} material={materials.PaletteMaterial036} position={[0.56, 1.401, -3.895]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_42.geometry} material={materials.PaletteMaterial037} position={[0.523, 1.41, -3.894]} rotation={[-Math.PI / 2, 0, -1.566]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_43.geometry} material={materials.PaletteMaterial038} position={[0.573, 1.405, -3.862]} rotation={[-Math.PI / 2, 0, 0.005]} scale={0.025} />
      <mesh geometry={nodes.Geom3D__2.geometry} material={materials['Metal Corrugated Shiny']} position={[2.852, 1.559, -4.281]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.025, 0.025, 0.025]} />
      <mesh geometry={nodes.Geom3D_44.geometry} material={materials['1']} position={[2.497, 1.176, -3.908]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.022, 0.032, 0.019]} />
      <mesh geometry={nodes.Geom3D_45.geometry} material={materials['2']} position={[2.497, 1.176, -3.908]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.022, 0.032, 0.019]} />
      <mesh geometry={nodes.Geom3D_46.geometry} material={materials['20240228_144641']} position={[2.497, 1.176, -3.908]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.022, 0.032, 0.019]} />
      <mesh geometry={nodes.Geom3D_47.geometry} material={materials['20240228_144008']} position={[2.497, 1.176, -3.908]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.022, 0.032, 0.019]} />
      <mesh geometry={nodes.Geom3D_48.geometry} material={materials['20240228_144054']} position={[2.497, 1.176, -3.908]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.022, 0.032, 0.019]} />
      <mesh geometry={nodes.Geom3D_49.geometry} material={materials.PaletteMaterial039} position={[1.182, 0.307, -2.001]} rotation={[-1.498, -0.011, 2.99]} scale={0} />
      <mesh geometry={nodes.Geom3D_50.geometry} material={materials.PaletteMaterial040} position={[1.177, 0.316, -1.975]} rotation={[-1.498, -0.011, 2.99]} scale={0} />
      <mesh geometry={nodes.Geom3D_51.geometry} material={materials.PaletteMaterial041} position={[1.191, 0.422, -2.071]} rotation={[-1.498, -0.011, 2.99]} scale={0} />
      <mesh geometry={nodes.Geom3D_52.geometry} material={materials.PaletteMaterial042} position={[1.361, 0.094, -2.122]} rotation={[-1.498, -0.011, 2.99]} scale={[0.025, 0.021, 0.025]} />
      <mesh geometry={nodes.Geom3D__3.geometry} material={materials.PaletteMaterial043} position={[0.648, 0.885, -2.565]} rotation={[0, -1.491, -Math.PI]} scale={0} />
      <mesh geometry={nodes.Geom3D__4.geometry} material={materials.PaletteMaterial044} position={[0.646, 0.892, -2.529]} rotation={[-Math.PI / 2, 0, 1.651]} scale={0} />
      <mesh geometry={nodes.Geom3D_53.geometry} material={materials.PaletteMaterial045} position={[0.792, 0.892, -2.516]} rotation={[0, -1.491, -Math.PI]} scale={0} />
      <mesh geometry={nodes.Geom3D_54.geometry} material={materials.PaletteMaterial046} position={[0.792, 0.892, -2.516]} rotation={[0, -1.491, -Math.PI]} scale={0} />
      <mesh geometry={nodes.Geom3D_55.geometry} material={materials.PaletteMaterial047} position={[0.792, 0.892, -2.516]} rotation={[0, -1.491, -Math.PI]} scale={0} />
      <mesh geometry={nodes.Geom3D__5.geometry} material={materials.PaletteMaterial048} position={[0.645, 0.892, -2.529]} rotation={[-Math.PI / 2, 0, 1.651]} scale={0} />
      <mesh geometry={nodes.Geom3D__6.geometry} material={materials.PaletteMaterial049} position={[0.648, 0.886, -2.561]} rotation={[Math.PI / 2, 0, 1.491]} scale={0} />
      <mesh geometry={nodes.Geom3D_56.geometry} material={materials.Tela} position={[0.789, 0.892, -2.519]} rotation={[-Math.PI / 2, 0, 1.651]} scale={0} />
      <mesh geometry={nodes.Geom3D_57.geometry} material={materials.PaletteMaterial050} position={[1.695, 0.703, -5.999]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_58.geometry} material={materials.Plywood_03_1K} position={[2.05, 0, -2.642]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes['Geom3D_Interior_Wood_Door_-_single'].geometry} material={materials.Plywood_08_1K} position={[2.05, 0, -2.642]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_59.geometry} material={materials['[Wood_Cherry_Original]']} position={[2.05, 0, -2.642]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_60.geometry} material={materials.PaletteMaterial051} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_61.geometry} material={materials.PaletteMaterial052} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_62.geometry} material={materials.PaletteMaterial053} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_63.geometry} material={materials['*3']} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_64.geometry} material={materials.PaletteMaterial054} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_65.geometry} material={materials.PaletteMaterial055} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_66.geometry} material={materials.PaletteMaterial056} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_67.geometry} material={materials.PaletteMaterial057} position={[0.915, 0.777, -3.881]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.008, 0.01, 0.012]} />
      <mesh geometry={nodes.Geom3D_68.geometry} material={materials.PaletteMaterial058} position={[1.127, 0.789, -3.891]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.007, 0.008, 0.01]} />
      <mesh geometry={nodes['Geom3D_4x1x1_vert_hinge_double#2'].geometry} material={materials.PaletteMaterial059} position={[2.737, 1.606, -3.643]} rotation={[-Math.PI, 0.705, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['Geom3D_2x1x1_vert_hinge_B#1'].geometry} material={materials.PaletteMaterial060} position={[2.733, 1.6, -3.657]} rotation={[-Math.PI, 0.705, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Geom3D__7.geometry} material={materials.PaletteMaterial061} position={[2.735, 1.593, -3.649]} rotation={[-Math.PI, 0.705, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.Geom3D__8.geometry} material={materials.PaletteMaterial062} position={[2.748, 1.593, -3.644]} rotation={[-Math.PI, 0.705, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_1x1_technic_peg.geometry} material={materials.PaletteMaterial063} position={[2.458, 1.6, -3.501]} rotation={[0, -1.098, 0]} scale={0.001} />
      <mesh geometry={nodes['Geom3D_1x1x13_cylinder#2'].geometry} material={materials.PaletteMaterial064} position={[2.716, 1.599, -3.593]} rotation={[-Math.PI / 2, 0, 2.044]} scale={0.001} />
      <mesh geometry={nodes.Geom3D_69.geometry} material={materials.PaletteMaterial065} position={[2.755, 1.605, -3.56]} rotation={[-Math.PI / 2, 0, 2.567]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_70.geometry} material={materials['*1']} position={[2.713, 1.609, -3.472]} rotation={[0, 0.473, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_71.geometry} material={materials['*6']} position={[2.691, 1.63, -3.623]} rotation={[-1.708, 0.116, -2.268]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_72.geometry} material={materials['*7']} position={[2.636, 1.606, -3.55]} rotation={[-1.143, -0.681, 2.197]} scale={0.021} />
      <mesh geometry={nodes.Geom3D__9.geometry} material={materials.PaletteMaterial066} position={[2.691, 1.585, -3.484]} rotation={[0, 0.473, 0]} scale={[0.021, 0.021, 0.018]} />
      <mesh geometry={nodes.Geom3D_73.geometry} material={materials.PaletteMaterial067} position={[2.812, 1.6, -3.547]} rotation={[-Math.PI / 2, 0, 2.044]} scale={[0.018, 0.017, 0.016]} />
      <mesh geometry={nodes['Geom3D_Component#83'].geometry} material={materials.PaletteMaterial068} position={[2.484, 1.579, -3.628]} rotation={[0, -1.098, 0]} scale={[0.021, 0.021, 0.02]} />
      <mesh geometry={nodes.Geom3D_74.geometry} material={materials.PaletteMaterial069} position={[2.484, 1.579, -3.628]} rotation={[0, -1.098, 0]} scale={[0.021, 0.021, 0.02]} />
      <mesh geometry={nodes.Geom3D_75.geometry} material={materials['*9']} position={[2.682, 1.606, -3.573]} rotation={[-1.998, 0.681, -0.944]} scale={[-0.021, 0.021, 0.021]} />
      <mesh geometry={nodes.Geom3D_76.geometry} material={materials.PaletteMaterial070} position={[2.635, 1.579, -3.593]} rotation={[-Math.PI / 2, 0, -1.093]} scale={0.021} />
      <mesh geometry={nodes.Geom3D__10.geometry} material={materials.PaletteMaterial071} position={[2.577, 1.606, -3.504]} rotation={[0, -1.098, Math.PI]} scale={0.021} />
      <mesh geometry={nodes.Geom3D__11.geometry} material={materials.PaletteMaterial072} position={[2.488, 1.612, -3.63]} rotation={[0, -1.098, -Math.PI / 2]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_77.geometry} material={materials['*4']} position={[2.626, 1.598, -3.518]} rotation={[-Math.PI / 2, 0, 2.044]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_78.geometry} material={materials['*10']} position={[2.627, 1.628, -3.611]} rotation={[-Math.PI / 2, 0, 0.473]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_79.geometry} material={materials['*8']} position={[2.653, 1.619, -3.558]} rotation={[-Math.PI / 2, 0, 2.044]} scale={0.021} />
      <mesh geometry={nodes.Geom3D_80.geometry} material={materials.PaletteMaterial073} position={[1.55, 0.055, -5.744]} rotation={[-Math.PI / 2, 0, -2.094]} scale={0.008} />
      <mesh geometry={nodes.Geom3D_81.geometry} material={materials.PaletteMaterial074} position={[1.55, 0.055, -5.744]} rotation={[-Math.PI / 2, 0, -2.094]} scale={0.008} />
      <mesh geometry={nodes.Geom3D_82.geometry} material={materials.Material__3_0_6} position={[0.547, 0.887, -2.55]} rotation={[-Math.PI / 2, 0, 1.401]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_83.geometry} material={materials['*5']} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/chambre-transformed.glb')
